#:include kv\homescreen.kv
#:include kv\settingsscreen.kv
#:include kv\carescreen.kv
GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        HomeScreen: 
            name: "home_screen"
            id: home_screen
        SettingsScreen:
            name: "settings_screen"
            id: settings_screen
        CareScreen:
            name: "care_screen"
            id: care_screen


